version: '3.8'

services:
  app:
    build: .
    command: pnpm dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - BOOK_SUBSCRIBER_ENABLED=true
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
